### ISSUE TITLE
MutiAdds

### ISSUE THREAD

**Issue by Auth0rM0rgan** [ChaofWang/AWSRN#5]
Hey @ChaofWang, 

Thanks for sharing the code. How did you count Mult-Adds of your models?

Thanks,

**Comment by ChaofWang** [comment]
@Auth0rM0rgan 
hello，since AWSRN consists of some normal convolution ops and almost all convolutions' input size is consistent, MutiAdds can be simply expressed as "model_param*input_width*input_height". But if the model contains some special ops, like group convolutions, or the input of each convolution op is different, it needs to be calculated layer by layer.

**Comment by Auth0rM0rgan** [comment]
Hey @ChaofWang, 
Thanks for the guide. Would you please tell me how should I calculate the MultiAdds for group convolutions?

Thanks,

**Comment by ChaofWang** [comment]
@Auth0rM0rgan sorry, my mistakes. group convolution also can calculate by params*H*W
